CREATE DATABASE LOJA_BRINQUEDOS;

CREATE TABLE ESTRUTURA(
	COD_ESTRUTURA INT PRIMARY KEY AUTO_INCREMENT,
    COD_EMPRESA INT NOT NULL,
    COD_SETOR INT NOT NULL,
    COD_FUNCIONARIO INT NOT NULL,
    CONSTRAINT PK_COD_ESTRUTURA PRIMARY KEY (COD_ESTRUTURA)
);

CREATE TABLE EMPRESA(
	COD_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    DC_ENDERECO VARCHAR(100) NOT NULL,
    NM_EMPRESA VARCHAR(100) NOT NULL,
    DC_CNPJ VARCHAR(14) NOT NULL,
    CONSTRAINT PK_COD_ESTRUTURA PRIMARY KEY (COD_EMPRESA)
);

CREATE TABLE SETOR(
	COD_SETOR INT PRIMARY KEY AUTO_INCREMENT,
    NM_SETOR VARCHAR(50) NOT NULL,
    CONSTRAINT PK_COD_ESTRUTURA PRIMARY KEY (COD_SETOR)
);

CREATE TABLE FUNCIONARIO(
	COD_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NM_FUNCIONARIO VARCHAR(100) NOT NULL,
    DC_CPF VARCHAR(11) NOT NULL,
	DC_EMAIL VARCHAR(100),
    DT_NASCIMENTO DATE,
    DC_TELEFONE VARCHAR(11),
    DC_ENDERECO VARCHAR(100),
    CONSTRAINT PK_COD_ESTRUTURA PRIMARY KEY (COD_FUNCIONARIO)
);

CREATE TABLE ACESSO(
	COD_FUNCIONARIO INT,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
	FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO)
);

/* CREATE TABLE ENDERECO(
	COD_ENDERECO INT,
    DC_LOGRADOURO VARCHAR(100) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
	FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO)
); */

CREATE TABLE CLIENTE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL, 
    TELEFONE VARCHAR(11) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL 
);

CREATE TABLE ESTOQUE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_ID INT AUTO_INCREMENT,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (FK_ID) REFERENCES PRODUTO(ID)
);

CREATE TABLE ITEM_PEDIDO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	QUANTIDADE INT NOT NULL, 
    PRECO DOUBLE NOT NULL
); 

CREATE TABLE PEDIDO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	FOREIGN KEY (ID) REFERENCES ITEM_PEDIDO(ID)
);

CREATE TABLE PRODUTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA VARCHAR(50) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(50) NULL,
    CLASSIFICACAO_IDADE VARCHAR(10) NULL,
    PRECO_UNITARIO DOUBLE NOT NULL,
    IMG_URL VARCHAR(100) NOT NULL
);

CREATE TABLE VENDA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_CLIENTE INT AUTO_INCREMENT,
	FK_ID_PEDIDO INT AUTO_INCREMENT,
    DATA_VENDA DATE NOT NULL, 
    STATUS_VENDA VARCHAR(25) NOT NULL, 
    FOREIGN KEY (FK_ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (FK_ID_PEDIDO) REFERENCES PEDIDO(ID)
);

/* decidir sobre a tabela de endereco, se é realemente necessario ou se pode ser substituido por uma só coluna 
--com o endereco completo. */